name: Check Lint and Tests

on:
  pull_request:
    branches: [ master, main ]

jobs:
  check_ktlint:
    name: Check ktlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Validate code using ktlint
        run: ./gradlew lintKotlinMain

  check_tests:
    needs: check_ktlint
    name: Check unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run unit tests (:core)
        run: ./gradlew :core:testDebugUnitTest
      - name: Run unit tests (:accounts)
        run: ./gradlew :accounts:testDebugUnitTest
      - name: Run unit tests (:in-app-payments)
        run: ./gradlew :in-app-payments:testDebugUnitTest