name: Check Lint and Tests

on:
  pull_request:
    branches: [ master, main ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

  check_ktlint:
    needs: setup
    name: Check ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate code using ktlint
        run: ./gradlew lintKotlinMain

  check_tests:
    needs: check_ktlint
    name: Check unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests (:core)
        run: ./gradlew :core:testDebugUnitTest
      - name: Run unit tests (:accounts)
        run: ./gradlew :accounts:testDebugUnitTest
      - name: Run unit tests (:in-app-payments)
        run: ./gradlew :in-app-payments:testDebugUnitTest